name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout your repository using git
              uses: actions/checkout@v4
            - name: Install pnpm
              run: npm install pnpm -g
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
    deploy:
            needs: build
            runs-on: ubuntu-latest
            steps:
              - name: Checkout your repository using git
                uses: actions/checkout@v4
              
              
              - name: remove old docs
                run: rm -rf docs/*
            # 推送到docs文件夹
              - name: Deploy
                uses: peaceiris/actions-gh-pages@v3
                with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs